services:
  - type: web
    name: student-enrollment
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn student_enrollment.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://StudentEnrollment_owner:npg_HlYBdmuI9KD5@ep-wandering-cell-a1v64843-pooler.ap-southeast-1.aws.neon.tech/StudentEnrollment?sslmode=require
      - key: DJANGO_SECRET_KEY
        value: af$7xl4irmwqr*hp&rplbv#1#(!(kawv5(&r-%$**&ejop5dgo
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "student-enrollment-system-u3nu.onrender.com"
