# Generated by Django 5.2 on 2025-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_enrolled'], 'permissions': [('moderator_access', 'Can access moderator features')]},
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_information',
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_contact',
            field=models.CharField(blank=True, help_text='Alternative contact number (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.TextField(blank=True, help_text="Parent's address if different from student", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text="Parent's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_full_name',
            field=models.CharField(help_text='Full name of parent or guardian', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_occupation',
            field=models.CharField(blank=True, help_text="Parent's occupation", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(help_text="Parent's primary phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_workplace',
            field=models.CharField(blank=True, help_text="Parent's workplace or company name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship',
            field=models.CharField(help_text='Relationship to student (e.g., Father, Mother, Guardian)', max_length=50, null=True),
        ),
    ]
